apiVersion: v1 
kind: ConfigMap
metadata:
  name: user
  namespace: roboshop
  labels:
    component: user
    project: roboshop
    tier: app
data:
  REDIS_URL: "redis://redis:6379"
  MONGO_URL: "mongodb://mongodb:27017/user"
  MONGO: "true"
---
apiVersion: apps/v1
kind: Deployment
metadata:   # deployment labeles
  name: user
  namespace: roboshop
  labels: 
    component: user
    project: roboshop
    tier: database
spec:
  replicas: 1
  selector:
    matchLabels: 
      component: user
      project: roboshop
      tier: database
  template:   # this is pod definition
    metadata:
      labels:
        component: user
        project: roboshop
        tier: database
    spec:
      containers:
      - name: user
        image: srikesh7117/user:v1
        envFrom:
        - configMapRef:
            name: user
---
apiVersion: v1 
kind: Service
metadata:
  name: user
  namespace: roboshop
  labels:
    component: user
    project: roboshop
    tier: database
spec: 
  selector: 
    component: user
    project: roboshop
    tier: database
  ports: 
  - protocol: TCP
    port: 8080
    targetPort: 8080